TecHealth/Mongo3/Mongo3/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;
using System.Configuration;
using Mongo3.App_Start;
using Mongo3.Models;

namespace Mongo3.Controllers
{
    public class FuncionariosController : Controller
    {
        private MongoDBContext dbcontext;
        private IMongoCollection<FuncionarioModel> funcionarioCollection; 

         public FuncionariosController()
        {
            dbcontext = new MongoDBContext();
            funcionarioCollection = dbcontext.database.GetCollection<FuncionarioModel>("Funcionario");
        }

        // GET: Funcionarios
        public ActionResult Index()
        {
            List<FuncionarioModel> funcionarios = funcionarioCollection.AsQueryable<FuncionarioModel>().ToList();
            return View(funcionarios);
        }

        // GET: Funcionarios/Details/5
        public ActionResult Details(string id)
        {
            var funcionarioId = new ObjectId(id);
            var funcionario = funcionarioCollection.AsQueryable<FuncionarioModel>().SingleOrDefault(x => x.Id == funcionarioId);
            return View(funcionario);
        }

        // GET: Funcionarios/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Funcionarios/Create
        [HttpPost]
        public ActionResult Create(FuncionarioModel funcionario)
        {
            try
            {
                funcionarioCollection.InsertOne(funcionario);

                return RedirectToAction("Index"); 
            }
            catch
            {
                return View();
            }
        }

        // GET: Funcionarios/Edit/5
        public ActionResult Edit(string id)
        {
            var funcionarioId = new ObjectId(id);
            var funcionario = funcionarioCollection.AsQueryable<FuncionarioModel>().SingleOrDefault(x => x.Id == funcionarioId);
            return View(funcionario);
           
        }

        // POST: Funcionarios/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, FuncionarioModel funcionario)
        {
            try
            {
                var filter = Builders<FuncionarioModel>.Filter.Eq("id_", ObjectId.Parse(id));
                var update = Builders<FuncionarioModel>.Update.Set("Nombre", funcionario.Nombre);//Se puede agregar mas haciendo un .Set("",) extra
                var result = funcionarioCollection.UpdateOne(filter, update);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Funcionarios/Delete/5
        public ActionResult Delete(string id)
        {
            var funcionarioId = new ObjectId(id);
            var funcionario = funcionarioCollection.AsQueryable<FuncionarioModel>().SingleOrDefault(x => x.Id == funcionarioId);
            return View(funcionario);
        }

        // POST: Funcionarios/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, FuncionarioModel funcionario)
        {
            try
            {
                funcionarioCollection.DeleteOne(Builders<FuncionarioModel>.Filter.Eq("_id", ObjectId.Parse(id)));

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Logged()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(FuncionarioModel user)
        {
            
                if (user.TipoFuncionario == "0")
                {
                    return RedirectToAction("Index");
                }
                    var usr = funcionarioCollection.AsQueryable<FuncionarioModel>().SingleOrDefault(u => u.Nombre == user.Nombre && u.Contraseña == user.Contraseña);
                //var usr = funcionarioCollection.FindAsync(u => u.Nombre == user.Nombre && u.Contraseña == user.Contraseña);
                
                if (usr != null)
                {

                    if (user.TipoFuncionario == "0")
                    {
                        return RedirectToAction("Index", "Citas");
                    }

                    if (user.TipoFuncionario == "1")
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return RedirectToAction("Index", "Citas");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Nombre de usuario o contraseña incorrectos");
                }
                return View();
            
        }
    }
}

TecHealth/Mongo3/Mongo3/Controllers/PacientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;
using System.Configuration;
using Mongo3.App_Start;
using Mongo3.Models;

namespace Mongo3.Controllers
{
    public class PacientesController : Controller
    {
        private MongoDBContext dbcontext;
        private IMongoCollection<PacienteModel> pacienteCollection;

        public PacientesController()
        {
            dbcontext = new MongoDBContext();
            pacienteCollection = dbcontext.database.GetCollection<PacienteModel>("Pacientes");
        }

        // GET: Funcionarios
        public ActionResult Index()
        {
            List<PacienteModel> pacientes = pacienteCollection.AsQueryable<PacienteModel>().ToList();
            return View(pacientes);
        }

        // GET: Funcionarios/Details/5
        public ActionResult Details(string id)
        {
            var pacientesId = new ObjectId(id);
            var pacientes = pacienteCollection.AsQueryable<PacienteModel>().SingleOrDefault(x => x.Id == pacientesId);
            return View(pacientes);
        }

        // GET: Funcionarios/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Funcionarios/Create
        [HttpPost]
        public ActionResult Create(PacienteModel pacientes)
        {
            try
            {
                pacienteCollection.InsertOne(pacientes);

                return RedirectToAction("Index"); 
            }
            catch
            {
                return View();
            }
        }

        // GET: Funcionarios/Edit/5
        public ActionResult Edit(string id)
        {
            var pacienteId = new ObjectId(id);
            var paciente = pacienteCollection.AsQueryable<PacienteModel>().SingleOrDefault(x => x.Id == pacienteId);
            return View(paciente);
           
        }

        // POST: Funcionarios/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, PacienteModel pacientes)
        {
            try
            {
                var filter = Builders<PacienteModel>.Filter.Eq("id_", ObjectId.Parse(id));
                var update = Builders<PacienteModel>.Update.Set("Nombre", pacientes.Nombre);//Se puede agregar mas haciendo un .Set("",) extra
                var result = pacienteCollection.UpdateOne(filter, update);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Funcionarios/Delete/5
        public ActionResult Delete(string id)
        {
            var pacientesId = new ObjectId(id);
            var pacientes = pacienteCollection.AsQueryable<PacienteModel>().SingleOrDefault(x => x.Id == pacientesId);
            return View(pacientes);
        }

        // POST: Funcionarios/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, PacienteModel pacientes)
        {
            try
            {
                pacienteCollection.DeleteOne(Builders<PacienteModel>.Filter.Eq("_id", ObjectId.Parse(id)));

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(PacienteModel user)
        {
                var usr = pacienteCollection.AsQueryable<PacienteModel>().SingleOrDefault(u => u.Nombre == user.Nombre && u.Contraseña == user.Contraseña);
                //var usr = funcionarioCollection.FindAsync(u => u.Nombre == user.Nombre && u.Contraseña == user.Contraseña);
                if (usr != null)
                {

                    return RedirectToAction("Index", "Citas");
                }
                else
                {
                    ModelState.AddModelError("", "Nombre de usuario o contraseña incorrectos");
                }
                return View();
            
        }
     }
    
}

TecHealth/Mongo3/Mongo3/Views/Pacientes/Index.cshtml
@model IEnumerable<Mongo3.Models.PacienteModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nacimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoSangre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nacionalidada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Residencia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefonos)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellido1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellido2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nacimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoSangre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nacionalidada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Residencia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefonos)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>

TecHealth/Mongo3/Mongo3/Views/Pacientes/Login.cshtml
@model Mongo3.Models.PacienteModel

@{
    ViewBag.Title = "Login";
}

<h2>Login Pacientes</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contraseña, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contraseña, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contraseña, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="LogIn" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Ir a logIn de funcionarios", "Login", "Funcionarios")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}